### PR TITLE
Update blip.runcom

### PR DESCRIPTION
**Pull request by ghost**
BLIP has an ENTRY so it's a subroutine not a main program. `NCLOAD BLIP` will fail with `NO MAIN PROGRAM`.

Reproducting:
```
ncload blip
W 1250.2
 NO MAIN PROGRAM
R .050+.000

ncload (org) blip blip
W 1251.3
R .050+.000
```

### CODE REVIEW

**Comment by ghost** [comment]
```
blip
W 1258.6
Type: Eek

R .000+.016

blip 0
W 1258.9
*
R .000+.000
```
It would be fun if the RRS 12-bit char could change the text to red.

**Comment by rcornwell** [comment]
Getting it to type in red text is hard since the change in text color would be done by the 7750 emulation, but this would have to know the terminal type it is connecting to do know how to change text color.

**Comment by ghost** [comment]
I don't expect to see ribbon color changing implemented any time soon. It was just me thinking about it. I'm not even sure if the 7750 plays a role in changing ribbon color or not. So much to learn.

**Comment by rcornwell** [comment]
Ribbon change was done by sending a control character to the terminal. The problem is that simH does not know the terminal type and how to change text color.

**Comment by ghost** [comment]
I actually don't use SIMH for 709x CTSS because it spins the host CPU while CTSS is idle. That causes too much heat and the fans come on etc. I use Dave's s709.  The same overheating issue existed for SIMH back when I was into PDP-11 emulation, I used Harti's P11 instead of SIMH. For PI ITS I used KLH-10 instead of SIMH.  I think SIMH PDP-10 ITS emulation may no longer spin the CPU, I used it from Lars' repo a while ago and I didn't notice any overheating.

**Comment by rcornwell** [comment]
It looks like I never added IDLE support to simH I7090 CPU. I can add it onto my queue. For ITS there are currently 4 SimH emulators to choose from Bob's PDP10, and my PDP10's. All of mine support idle under ITS. I have never noticed excessive fans on my systems. I will add IDLE support to I7090 when I get some time. For S709 I have not looked much at Dave's emulator to understand how it works.

**Comment by ghost** [comment]
Thanks, I'm really grateful for you.

**Pull request merged**
